#!/usr/bin/env python
# -*- encoding: utf-8 -*-
lst = """Time – Die Zeit
Man – Der Man
Hand – Die Hand
Day – Der Tag
Way – Der Weg
Eye – Das Auge
Thing – Das Ding
Head – Der Kopf
Year – Das Jahr
Room – Die Raum
Door – Die Tür
Woman – Die Frau
Face – Das Gesicht
Mother – Die Mutter
People – Das Volk
Night – Die Nacht
House – Das Haus
Father – Der Vater
Life – Das Leben
Back – Der Rücken
Voice – Die Stimme
Girl – Das Mädchen
Place – Der Ort
Boy – Der Junge
Car – Das Auto
Side – Die Seite
Arm – Der Arm
Child – Das Kind
Word – Das Wort
Moment – Der Moment
Hair – Das Haar
Foot – Der Fuß
Water – Das Wasser
Light – Das Licht
World – Die Welt
Name – Der Name
Friend – Der Freund
Window – Das Fenster
Body – Der Körper
Table – Der Tisch
Morning – Der Morgen
Bed – Das Bett
Wall – Die Mauer
Street – Die Straße
School – Die Schule
Air – Die Luft
Floor – Der Boden
Hour – Die Stunde
End – Das Ende
Family – Die Familie
Guy – Der Kerl
Kind – Die Art
Minute – Die Minute
Story – Die Geschichte
God – Der Gott
Week – Die Woche
Work – Die Arbeit
Shoulder – Die Schulter
Part – Der Teil
Mind – Der Geist
Book – Das Buch
Finger – Der Finger
Mouth – Der Mund
Kid – Das Kind
Glass – Das Glas
Tree – Der Baum
Sound – Der Klang
Line – Die Linie
Wife – Die Ehefrau
Heart – Das Herz
Money – Das Geld
Phone – Das Telefon
Look – Das Aussehen
Leg – Das Bein
Chair – Der Stuhl
Office – Das Büro
Brother – Der Bruder
Question – Die Frage
City – Die Stadt
Month – Der Monat
Baby – Das Baby
Home – Das Zuhause
Dog – Der Hund
Road – Die Straße
Idea – Die Idee
Kitchen – Die Küche
Lot – Das Los
Son – Der Sohn
Job – Der Beruf
Paper – Das Papier
Sister – Die Schwester
Smile – Das Lächeln
Point – Der Punkt
Thought – Der Gedanke
Love – Die Liebe
Town – Die Stadt
Death – Der Tod
Ground – Der Boden
Others – Die Anderen
Fire – Das Feuer
Step – Der Schritt
Blood – Das Blut
Fact – Die Tatsache
Breath – Der Atem
Lip – Die Lippe
Sun – Die Sonne
Building – Gebäude
Number – Die Anzahl
Husband – Der Ehemann
Parent – Das Elternteil
Corner – Die Ecke
Problem – Das Problem
Couple – Das Ehepaar
Daughter – Die Tochter
Bag – Der Beutel
Hell – Die Hölle
Rest – Die Rast
Business – Das Geschäft
Sky – Der Himmel
Box – Die Kiste
Person – Die Person
Reason – Der Grund
Right – Das Recht
Skin – Die Haut
Dad – Der Vater
Case – Der Fall
Piece – Das Stück
Doctor – Der Doktor
Edge – Die Ecke
Mom – Die Mama
Picture – Das Bild
Sense – Der Sinn
Ear – Das Ohr
Second – Der Zweite
Lady – Die Dame
Neck – Der Hals
Wind – Der Wind
Desk – Der Schreibtisch
Gun – Die Waffe
Stone – Der Stein
Coffee – Der Kaffee
Ship – Das Schiff
Earth – Die Erde
Food – Das Essen
Horse – Das Pferd
Field – Das Feld
War – Der Krieg
Afternoon – Der Nachmittag
Sir – Die Sir
Space – Der Raum
Evening – Der Abend
Letter – Der Brief
Bar – Die Bar
Dream – Der Traum
Apartment – Die Wohnung
Chest – Die Brust
Game – Das Spiel
Summer – Der Sommer
Matter – Der Grund
Silence – Die Stille
Top – Die Spitze
Rock – Der Fels
Power – Die Macht
Clothes – Die Kleider
Sign – Das Schild
Attention – Die Aufmerksamkeit
Music – Die Musik
State – Der Staat
Pocket – Die Tasche
Dinner – Das Abendessen
Hall – Die Halle
Pain – Der Schmerz
Age – Das Alter
River – Der Fluss
Chance – Die Chance
Nose – Die Nase
Shadow – Der Schatten
Police – Die Polizei
Memory – Das Gedächtnis
Color – Die Farbe
Knee – Das Knie
Wood – Das Holz
Shirt – Das Hemd
Party – Die Party
Country – Das Land
Truck – Der Lkw
Tooth – Der Zahn
Bill – Die Rechnung
Scene – Die Szene
Land – Das Land
Star – Der Stern
Bird – Der Vogel
Bedroom – Das Schlafzimmer
Uncle – Der Onkel
Sort – Die Art
Group – Die Gruppe
Truth – Die Wahrheit
Trouble – Die Schwierigkeiten
Crowd – Die Menge
Station – Der Bahnhof
Tear – Die Reiß
Class – Die Klasse
Sea – Das Meer
Animal – Das Tier
Center – Das Zentrum
Feeling – Das Gefühl
Store – Das Geschäft
Mountain – Der Berg
News – Die Nachrichten
Shoe – Der Schuh
Cat – Die Katze
Screen – Der Bildschirm
Bottle – Die Flasche
Call – Der Anruf
Living – Die Lebenden
Cheek – Die Wange
Student – Der Schüler
Ball – Der Ball
Sight – Die Sehenswürdigkeit
Hill – Der Hügel
Company – Das Unternehmen
Church – Die Kirche
Rain – Der Regen
Suit – Der Anzug
One – Der Eine
Direction – Die Richtung
Will – Der Wille
Throat – Der Hals
Middle – Die Mitte
Answer – Die Antwort
Stuff – Das Zeug
Hospital – Das Krankenhaus
Camera – Die Kamera
Dress – Das Kleid
Card – Die Karte
Yard – Der Hof
Dark – Die Dunkelheit
Shit – Die Scheiße
Image – Das Bild
Machine – Die Maschine
Distance – Die Distanz
Area – Das Gebiet
Narrator – Der Erzähler
Ice – Das Eis
Snow – Der Schnee
Note – Die Notiz
Mirror – Der Spiegel
King – Der König
Fear – Die Angst
Officer – Der Offizier
Hole – Das Loch
Shot – Der Schuss
Guard – Der Wächter
Conversation – Die Unterhaltung
Boat – Das Boot
System – Das System
Care – Die Pflege
Bit – Die Bit
Movie – Der Film
Bone – Der Knochen
Page – Die Seite
Captain – Der Kapitän
Aunt – Die Tante
Darkness – Dunkelheit
Control – Die Kontrolle
Drink – Das Getränk
Hotel – Das Hotel
Coat – Der Mantel
Stair – Die Treppen
Order – Die Bestellung
Rose – Die Rose
Miss – Der Fehl
Hat – Der Hut
Gold – Das Gold
Cigarette – Die Zigarette
Cloud – Die Wolke
View – Die Aussicht
Driver – Der Fahrer
Cup – Die Tasse
Figure – Die Figur
Expression – Der Ausdruck
Path – Der Pfad
Key – Der Schlüssel
Computer – Der Computer
Flower – Die Blume
Ring – Der Ring
Bathroom – Das Bad
Metal – Das Metall
Moon – Der Mond
Song – Das Lied
Soldier – Der Soldat
Radio – Das Radio
History – Die Geschichte
Wave – Die Welle
Plan – Der Plan
College – Das College
Fish – Der Fisch
Garden – Der Garten
Train – Der Zug
Shop – Das Geschäft
Cop – Der Polizist
Art – Die Kunst
Beer – Das Bier
North – Norden
Island – Die Insel
Bus – Der Bus
Smell – Der Geruch
Noise – Das Geräusch
Mama – Die Mama
Park – Der Park
South – Der Süden
Pair – Das Paar
Lord – Der Herr
Plate – Der Teller
Jacket – Die Jacke
Help – Die Hilfe
Daddy – Der Papa
Grass – Das Gras
Thanks – Die Dank
Heat – Die Hitze
Sleep – Der Schlaf
Brain – Das Gehirn
Service – Der Service
Trip – Die Reise
Beat – Der Beat
Knife – Das Messer
Spot – Der Platz
Message – Die Nachricht
Mark – Die Note
Teacher – Der Lehrer
Gaze – Der Blick
Village – Das Dorf
Winter – Der Winter
Front – Die Front
Law – Das Gesetz
Surface – Die Oberfläche
Bank – Die Bank
Team – Das Team
Maximum – Das Maximum
Position – Die Position
Stomach – Der Bauch
Turn – Die Wende
West – Der Westen
Lunch – Das Mittagessen
Change – Der Wechsel
Creature – Die Kreatur
Soul – Die Seele
Leaf – Das Blatt
Show – Die Show
Gate – Die Gate
Palm – Die Palme
Plastic – Der Kunststoff
Force – Die Kraft
Beach – Der Strand
President – Der Präsident
Shape – Die Form
Smoke – Der Rauch
Wheel – Das Rad
Silver – Das Silber
Roof – Das Dach
Weight – Das Gewicht
Tongue – Die Zunge
Tea – Der Tee
Track – Die Strecke
Angle – Der Winkel
Form – Die Form
Tone – Der Ton
Circle – Der Kreis
Spring – Der Frühling
Porch – Die Vorhalle
Sheet – Das Blatt
Member – Das Mitglied
Pool – Das Schwimmbecken
Need – Das Bedürfnis
Hope – Die Hoffnung
Lake – Der See
Breast – Die Brust
Surprise – Die Überraschung
Interest – Die Interesse
Bottom – Der Boden
Spirit – Der Geist
Block – Der Block
Language – Die Sprache
Bridge – Die Brücke
Dust – Staub
Cell – Die Zelle
Wine – Wein
Boot – Das Boot
Choice – Die Wahl
Row – Die Reihe
Talk – Das Gespräch
Plane – Das Flugzeug
Watch – Die Uhr
Information – Die Information
Grandmother – Die Großmutter
Wing – Der Flügel
Bob – Die Bob
Club – Der Club
Master – Der Meister
Grace – Die Gnade
Forest – Der Wald
Size – Die Größe
Set – Der Satz
Marriage – Die Ehe
Forehead – Die Stirn
Storm – Sturm
Doorway – Die Türöffnung
Situation – Die Situation
Counter – Der Zähler
Neighbor – Der Nachbar
Photo – Das Foto
Stage – Die Bühne
Meeting – Das Treffen
Nurse – Die Krankenschwester
Security – Die Sicherheit
Weapon – Die Waffe
Event – Das Ereignis
Ceiling – Die Decke
Engine – Der Motor
Gift – Das Geschenk
Restaurant – Das Restaurant
Board – Die Tafel
Hallway – Der Flur
Army – Die Armee
Effort – Der Aufwand
East – Der Osten
Agent – Der Agent
Future – Die Zukunft
Pant – Die Hose
Leather – Das Leder
Flight – Der Flug
Sex – Das Geschlecht
Court – Das Gericht
Course – Der Kurs
Dirt – Der Dreck
Egg – Das Ei
Chin – Das Kinn
Stranger – Der Fremde
Pleasure – Die Freude
Detail – Das Detail
Crew – Die Besatzung
Fall – Der Herbst
Guest – Der Gast
Experience – Das Erlebnis
Joke – Der Witz
Sand – Der Sand
Fist – Die Faust
Action – Die Aktion
Walk – Das Wandern
Wedding – Die Hochzeit
Deal – Der Deal
Nature – Die Natur
Planet – Der Planet
Cousin – Der Cousin
Movement – Die Bewegung
Flesh – Das Fleisch
Record – Der Datensatz
Camp – Das Camp
Newspaper – Die Zeitung
Ray – Der Strahl
Human – Der Mensch
Couch – Das Sofa
Motion – Die Bewegung
Grandfather – Der Großvater
Photograph – Die Fotografie
Secret – Das Geheimnis
Beauty – Die Schönheit
Presence – Das Vorhandensein
Bell – Die Glocke
Folk – Die Volks
Button – Der Knopf
List – Die Liste
Level – Das Level
Date – Das Datum
Subject – Das Thema
Difference – Der Unterschied
Pause – Die Pause
Van – Der Van
Blade – Die Klinge
Television – Das Fernsehen
Cover – Die Titelseite
Past – Die Vergangenheit
Farm – Der Bauernhof
Lap – Die Runden
Band – Die Band
Lawyer – Der Anwalt
Magazine – Das Magazin
Branch – Der Ast
Frame – Der Rahmen
Deck – Das Deck
Effect – Der Effekt
Dance – Der Tanz
Vision – Die Sicht
Ghost – Das Gespenst
Ass – Der Esel
Character – Der Charakter
Glance – Der Blick
GoodBye – Das Auf Wiedersehen
Parking – Das Park
Breakfast – Das Frühstück
Gesture – Die Geste
Luck – Das Glück
Blanket – Die Decke
Gas – Das Gas
Corridor – Der Korridor
Professor – Der Professor
Play – Das Spiel
Mistake – Der Fehler
University – Die Universität
Ocean – Der Ozean
Century – Das Jahrhundert
Honey – Der Honig
Pile – Der Stapel
Bowl – Die Schale
Base – Basis
Fence – Der Zaun
Rule – Die Regel
Laughter – Das Gelächter
Anger – Die Wut
Sweat – Der Schweiß
Accident – Der Unfall
Weather – Das Wetter
Decision – Die Entscheidung
Angel – Der Engel
Strength – Die Stärke
Chicken – Das Huhn
Study – Die Studium
Tape – Das Band
Wrist – Das Handgelenk
Stop – Der Halt
Hip – Die Hüfte
Government – Die Regierung
Belly – Der Bauch
Queen – Die Königin
Report – Bericht
Tail – Der Schweif
Plant – Die Pflanze
Flame – Die Flamme
Heaven – Der Himmel
Belt – Der Gürtel
Neighborhood – Die Nachbarschaft
Energy – Die Energie
Green – Das Grün
Quarter – Das Viertel
Enemy – Der Feind
Move – Die Bewegung
Entrance – Der Eingang
Library – Die Bibliothek
Writer – Der Verfasser
Peace – Der Frieden
Touch – Die Berührung
Pot – Der Topf
Type – Der Typ
Cause – Der Grund
Rope – Das Seil
Muscle – Der Muskel
Painting – Das Gemälde
Curtain – Die Gardine
Meal – Die Mahlzeit
Act – Der Akt
Wolf – Der Wolf
Cabin – Die Kajüte
Charge – Die Ladung
Clock – Die Uhr
Passenger – Der Passagier
Buddy – Der Kumpel
Drug – Das Medikament
Use – Die Verwendung
Bench – Die Bank
Traffic – Der Verkehr
Relief – Das Relief
Cap – Die Kappe
Pack – Das Rudel
Weekend – Das Wochenende
Stand – Der Stand
Elevator – Der Aufzug
Birthday – Der Geburtstag
Lily – Die Lilie
Iron – Das Bügeleisen
Meat – Das Fleisch
Eyebrow – Die Augenbraue
Response – Die Antwort
Speed – Die Geschwindigkeit
Purpose – Die Absicht
Skirt – Der Rock
Square – Das Quadrat
Drive – Die Fahrt
Article – Den Artikel
English – Das Englisch
Tower – Der Turm
Battle – Der Kampf
Film – Der Film
Race – Das Rennen
Shock – Der Schock
Section – Die Sektion
Manner – Die Methode
Sword – Das Schwert
Stick – Der Stock
File – Die Datei
Bread – Das Brot
Oil – Das Öl
Chain – Die Kette
Department – Die Abteilung
Project – Projekt
Murder – Der Mord
Bear – Der Bär
Test – Der Test
Visit – Der Besuch
Milk – Die Milch
Boss – Der Chef
Elbow – Der Ellbogen
Desire – Das Verlangen
Patient – Der Patient
Grin – Das Grinsen
Lover – Der Liebhaber
Price – Der Preis
Map – Die Karte
Knowledge – Das Wissen
Beginning – Der Anfang
Cold – Die Kälte
Closet – Der Schrank
Dawn – Die Morgendämmerung
Temple – Der Tempel
Joy – Der Spaß
Duty – Die Pflicht
Practice – Die Übung
Heel – Die Ferse
Valley – Das Tal
Fight – Der Kampf
Wire – Das Kabel
Jeans – Die Jeans
Kiss – Der Kuss
Jaw – Der Kiefer
Run – Die Lauf
Hold – Der Halt
Relationship – Das Verhältnis
Object – Das Objekt
Attack – Der Angriff
Dish – Das Gericht
Highway – Die Autobahn
Shade – Die Schattierung
Crime – Das Verbrechen
White – Das Weiß
Partner – Der Partner
Priest – Der Priester
Lawn – Der Rasen
Laugh – Das Lachen
Trunk – Der Kofferraum
Cry – Das Weinen
Program – Das Programm
Ride – Die Fahrt
Shelf – Das Regal
Gentleman – Der Gentleman
Being – Das Sein
Steel – Der Stahl
Sidewalk – Der Bürgersteig
Uniform – Die Uniform
Pattern – Das Muster
Evidence – Der Beweis
Player – Der Spieler
Novel – Der Roman
Pillow – Das Kissen
Lamp – Die Lampe
Drawer – Die Schublade
Danger – Die Gefahr
Detective – Der Detektiv
Instant – Die Instant
Thinking – Das Denken
Crack – Der Riss
Prayer – Das Gebet
Towel – Das Handtuch
Glove – Der Handschuh
Bay – Die Bucht
Audience – Das Publikum
Can – Die Dose
Condition – Die Bedingung
Trail – Der Pfad
Waist – Die Taille
Pressure – Der Druck
Telephone – Das Telefon
Sink – Das Waschbecken
Return – Die Rückkehr
Breeze – Die Brise
Taste – Der Geschmack
Fault – Der Fehler
Stream – Der Strom
Result – Das Ergebnis
Author – Der Autor
Tip – Das Trinkgeld
Shower – Die Dusche
Toe – Die Zehe
Season – Die Jahreszeit
Half – Die Hälfte
Fool – Der Dummkopf
Tunnel – Der Tunnel
Client – Der Klient
Garage – Die Garage
Mission – Die Mission
Chief – Der Chef
Bullet – Die Kugel
Market – Der Markt
Loss – Der Verlust
Series – Die Reihe
Pen – Der Stift
Term – Der Begriff
Poem – Das Gedicht
Prince – Der Prinz
Clay – Der Ton
Lock – Das Schloss
Reality – Die Realität
Snake – Die Schlange
Apple – Der Apfel
Mask – Die Maske
Customer – Dem Kunden
Birth – Die Geburt
Break – Die Pause
Wonder – Das Wunder
Sunlight – Das Sonnenlicht
Tank – Der Panzer
Staff – Das Personal
Lie – Die Lüge
Faith – Der Glaube
Honor – Die Ehre
Cream – Die Creme
Sake – Das Wohl
Victim – Das Opfer
Possibility – Die Möglichkeit
Contact – Der Kontakt
Mood – Die Stimmung
Thumb – Der Daumen
Reading – Das Lesen
Fun – Der Spaß
Candle – Die Kerze
Cave – Die Höhle
Post – Die Post
Prison – Das Gefängnis
Emotion – Die Emotion
Leader – Der Führer
Degree – Der Grad
Feature – Die Eigenschaft
Ticket – Das Ticket
Alien – Das Alien
Lesson – Der Unterricht
Desert – Die Wüste
Cut – Der Schnitt
Mess – Die Unordnung
Warning – Die Warnung
Tale – Das Märchen
Funeral – Das Begräbnis
Cab – Das Taxi
Reporter – Der Reporter
Present – Das Geschenk
Theater – Das Theater
Length – Die Länge
Mud – Der Schlamm
Science – Die Wissenschaft
Drop – Der Fall
String – Die Schnur
Speech – Die Rede
Copy – Die Kopie
Cow – Die Kuh
Worker – Der Arbeiter
Thigh – Der Oberschenkel
Lab – Das Labor
Roll – Die Rolle
Fruit – Das Obst
Patch – Der Patch
Silk – Die Seide
Buck – Der Buck
Brick – Die Ziegel
Rifle – Das Gewehr
Career – Die Karriere
Issue – Das Thema
Opportunity – Die Gelegenheit
Director – Der Direktor
Monster – Das Monster
Vehicle – Das Fahrzeug
Alley – Die Gasse
Sleeve – Die Hülse
Grave – Das Grab
Bush – Der Busch
Dining – Der Speisesaal
Opening – Die Eröffnung
Twin – Der Zwilling
Barn – Die Scheune
Pound – Das Pfund
Site – Der Standort
Flash – Der Blitz
Judge – Der Richter
Mass – Die Masse
Process – Der Prozess
Tie – Das Band
Purse – Der Geldbeutel
Pipe – Das Rohr
Dragon – Der Drache
Horizon – Der Horizont
Tray – Die Schale
Envelope – Der Umschlag
Check – Die Prüfung
Adult – Die Erwachsene
Emergency – Der Notfall
Material – Das Material
Childhood – Die Kindheit
Habit – Die Angewohnheit
Artist – Der Künstler
Address – Die Adresse
Scent – Der Duft
Universe – Das Universum
Nod – Das Kopfnicken
Shell – Die Muschel
Community – Die Gemeinde
Start – Der Anfang
Wound – Die Wunde
Mouse – Die Maus
Pilot – Der Pilot
Grade – Die Klasse
Video – Das Video
Basket – Der Korb
Wagon – Der Wagen
Attempt – Der Versuch
Sofa – Das Sofa
Cake – Der Kuchen
Fellow – Der Kerl
Affair – Die Affäre
Shore – Die Küste
General – Die Allgemeine
Root – Der Ursprung
Robe – Die Robe
Concern – Die Sorge
Press – Die Presse
Rat – Die Ratte
Society – Die Gesellschaft
Style – Der Stil
County – Die Kreis
Command – Der Befehl
Visitor – Der Besucher
Model – Das Model
Chamber – Die Kammer
Beast – Das Biest
Bunch – Das Bündel
Background – Der Hintergrund
Unit – Die Einheit
Furniture – Die Möbel
Nail – Der Nagel
Scream – Der Schrei
Property – Die Eigenschaft
Equipment – Die Ausrüstung
Driveway – Die Auffahrt
Grip – Der Griff
Tube – Das Rohr
Ash – Die Asche
Fan – Der Fan
Opinion – Die Meinung
Data – Die Daten
Connection – Die Verbindung
Trick – Der Trick
Mystery – Das Mysterium
Period – Die Periode
Writing – Das Schreiben
Horror – Der Horror
Candy – Die Süßigkeit
Bitch – Die Bitch
Health – Die Gesundheit
Manager – Der Geschäftsführer
Safety – Die Sicherheit
Height – Die Höhe
Appearance – Die Erscheinung
Sigh – Der Seufzer
Mine – Die Mine
Cloth – Die Kleidung
Reaction – Die Reaktion
Source – Die Quelle
Self – Das Ich
Pistol – Die Pistole
Airport – Der Flughafen
Hero – Der Held
Promise – Das Versprechen
Bow – Der Bogen
Tent – Das Zelt
Booth – Der Messestand
Cash – Das Geld
Avenue – Die Straße
TShirt – Das TShirt
Carpet – Der Teppich
Basement – Der Keller
Girlfriend – Die Freundin
Beard – Der Bart
Brow – Die Stirn
Display – Der Bildschirm
Signal – Das Signal
Servant – Der Diener
Whisper – Das Flüstern
Doubt – Der Zweifel
Account – Das Konto
Magic – Die Magie
Hank – Die Hank
Limb – Das Glied
Bastard – Der Bastard
Skull – Der Schädel
Sentence – Der Satz
Collar – Der Kragen
Horn – Das Horn
Oak – Die Eiche
Ankle – Der Knöchel
Doll – Die Puppe
Sandwich – Das Sandwich
Robin – Das Rotkehlchen
Justice – Die Justiz
Pride – Der Stolz
Youth – Die Jugend
Secretary – Der Sekretär
Research – Die Forschung
Sport – Der Sport
Task – Die Aufgabe
Grant – Der Zuschuss
Sheriff – Der Sheriff
Midnight – Die Mitternachts
Chip – Der Chip
Theory – Die Theorie
Alarm – Den Wecker
Collection – Die Sammlung
Cross – Das Kreuz
Pine – Die Kiefer
Generation – Die Generation
Authority – Die Autorität
Papa – Die Papa
Journey – Die Reise
Pearl – Die Perle
Toilet – Die Toilette
Killer – Der Mörder
Tool – Das Werkzeug
Medicine – Die Medizin
Sugar – Der Zucker
Princess – Die Prinzessin
Argument – Das Argument
Cliff – Die Klippe
Cart – Der Wagen
Crystal – Der Kristall
Bean – Die Bohne
Cage – Der Käfig
Chocolate – Die Schokolade
Coast – Die Küste
Decade – Das Jahrzehnt
Meaning – Die Bedeutung
Gear – Das Getriebe
Suitcase – Der Koffer
Operation – Die Operation
Breathing – Das Atem
Role – Die Rolle
Version – Die Version
Prisoner – Der Gefangene
Match – Das Match
Beam – Der Strahl
Castle – Die Burg
Rush – Der Ansturm
Lane – Die Fahrspur
Clothing – Die Bekleidung
Pole – Der Pol
Freedom – Die Freiheit
Skill – Das Können
Passion – Die Leidenschaft
Activity – Die Aktivität
Fuck – Zum Teufel
Platform – Die Platform
Salt – Das Salz
Bike – Das Fahrrad
Stack – Der Stapel
Companion – Der Begleiter
Fate – Das Schicksal
Rage – Die Wut
Supply – Die Versorgung
Whale – Der Wal
Pig – Das Schwein
Rabbit – Der Hase
Aisle – Der Gang
Monitor – Der Bildschirm
Helmet – Der Helm
Respect – Der Respekt
Excitement – Die Aufregung
Lobby – Die Lobby
Boyfriend – Der Freund
Fur – Das Fell
Range – Der Bereich
Dick – Die Dick
Code – Der Code
Chapter – Das Kapitel
Reflection – Die Reflexion
Mail – Die Post
Fly – Der Flug
Cabinet – Das Kabinett
Toy – Das Spielzeug
Baseball – Die Baseball
Inside – Das Innere
Pace – Die Geschwindigkeit
Handle – Der Griff
Lead – Die Führung
Amount – Die Summe
Nerve – Der Nerv
Terror – Der Schrecken
Sweater – Der Pullover
Quality – Die Qualität
Hunter – Der Jäger
Paint – Die Farbe
Buster – Die Buster
Cotton – Die Baumwolle
Sergeant – Der Wachtmeister
Credit – Der Kredit
Blow – Der Schlag
Devil – Der Teufel
Threat – Die Bedrohung
Success – Der Erfolg
Eve – Dem Vorabend
Cable – Das Kabel
Pan – Die Pfanne
Clerk – Der Angestellte
Title – Den Titel
Meter – Das Messgerät
Shame – Die Schande
Needle – Die Nadel
Lung – Die Lunge
Warrior – Der Krieger
Circumstance – Der Umstand
Studio – Das Studio
Panic – Die Panik
Lack – Der Mangel
Farmer – Der Bauer
Accent – Der Akzent
Bomb – Die Bombe
Panel – Die Platte
Ability – Die Fähigkeit
Fortune – Das Glück
Victor – Der Sieger
Feather – Die Feder
Grandma – Die Oma
Glow – Das Glühen
Behavior – Das Verhalten
Passage – Der Durchgang
Slave – Die Slave
Lieutenant – Der Leutnant
Barrel – Der Lauf
Warmth – Die Wärme
Impression – Der Eindruck
Mason – Der Maurer
Bride – Die Braut
Package – Das Paket
Fog – Der Nebel
Walking – Das Gehen
Balance – Die Balance
Sock – Die Socke
Robot – Der Roboter
Potato – Die Kartoffel
Item – Der Gegenstand
Bath – Das Bad
Diamond – Der Diamant
Corpse – Die Leiche
Explanation – Die Erklärung
Structure – Die Struktur
Exit – Der Ausgang
Pad – Das Pad
Stove – Der Herd
Blue – Das Blaue
American – Die Amerikaner
Ruby – Der Rubin
Lightning – Der Blitz
Pit – Die Grube
Colonel – Der Oberst
Dock – Das Dock
Creek – Der Bach
Advice – Der Ratschlag
Tourist – Der Tourist
Grief – Die Trauer
Defense – Die Verteidigung
Bite – Der Biss
Museum – Das Museum
Favor – Die Gunst
Supper – Das Abendessen
Comfort – Der Komfort
Dean – Der Dekan
Value – Der Wert
March – Der Marsch
Estate – Das Anwesen
Poet – Der Poet
Palace – Der Palast
Soup – Die Suppe
Nation – Die Nation
Jar – Das Gefäss
Standing – Der Ständige
Sack – Der Sack
Demon – Der Dämon
Conference – Die Konferenz
Juice – Der Saft
Responsibility – Die Verantwortung
Brush – Der Pinsel
Route – Die Route
Cheese – Der Käse
Hood – Die Haube
Duck – Die Ente
Saint – Der Heilige
Pass – Der Pass
Target – Das Ziel
Orange – Die Orange
Culture – Die Kultur
Tour – Die Reise
Commander – Der Kommandant
Hook – Der Haken
Mist – Der Nebel
Training – Das Training
Search – Die Suche
Coin – Die Münze
Miracle – Das Wunder
Advantage – Der Vorteil
Exchange – Der Austausch
Fiction – Die Fiktion
Pond – Der Teich
Assistant – Der Assistent
Design – Das Design
Fishing – Die Angel
Slope – Die Piste
Earl – Der Graf
Comment – Kommentar
Waiter – Der Kellner
Grocery – Von Lebensmittel
Ladder – Die Leiter
Curve – Die Kurve
Volume – Das Volumen
Risk – Das Risiko
Nightmare – Der Albtraum
Existence – Die Existenz
Trace – Die Spur
Disease – Die Krankheit
Support – Die Unterstützung
Witness – Der Zeuge
Stock – Die Aktie
Device – Das Gerät
Landscape – Die Landschaft
Holiday – Der Urlaub
Ace – Das Ass
Piano – Das Klavier
Gut – Die Eingeweide
Talent – Das Talent
Imagination – Die Phantasie
Black – Die Schwarze
Reed – Der Reed
Lid – Der Deckel
Hint – Der Hinweis
Walker – Der Wanderer
Chill – Die Kälte
Trial – Die Studie
Interview – Das Interview
Approach – Der Ansatz
Scar – Die Narbe
Fashion – Die Mode
Channel – Der Kanal
Footstep – Die Tritt
Pickup – Der Aufnehmer
Hawk – Der Habicht
Trailer – Der Anhänger
Statue – Die Statue
Pill – Die Pille
Bug – Der Käfer
Bucket – Der Eimer
Vacation – Den Urlaub
Species – Die Arten
Column – Die Kolumne
Damage – Der Schaden
Instrument – Das Instrument
Port – Der Hafen
Layer – Die Schicht
Strip – Der Streifen
Garbage – Der Müll
Rib – Die Rippe
Notebook – Das Notebook
Corn – Der Mais
Offer – Das Angebot
Drawing – Die Zeichnung
Statement – Die Aussage
Intelligence – Die Intelligenz
Excuse – Die Entschuldigung
Landing – Die Landung
Copyright – Der Urheberrechts
Rod – Die Stange
Fantasy – Die Fantasie
Curiosity – Die Neugier
Gown – Das Kleid
Border – Die Grenze
Poetry – Die Poesie
Firm – Die Firma
Rise – Der Aufgang
Handful – Die Handvoll
China – Die China
French – Die Franzosen
Mean – Die Durchschnitts
Deer – Das Reh
Print – Die Druck
Rail – Die Schiene
Rate – Die Rate
Courage – Der Mut
Arrival – Die Ankunft
Wish – Der Wunsch
Ridge – Der Grat
Idiot – Der Idiot
Bull – Der Bulle
Seed – Die Saat
Progress – Der Fortschritt
Feel – Das Gefühl
Shorts – Die Shorts
Citizen – Der Bürger
Trash – Der Müll
Log – Das Protokoll
Patience – Die Geduld
Bat – Die Fledermaus
Football – Der Fußball
Routine – Die Routine
Explosion – Die Explosion
Content – Der Inhalt
Scientist – Der Wissenschaftler
Failure – Das Versagen
Sin – Die Sünde
Butt – Der Hintern
Confusion – Die Verwirrung
Understanding – Das Verständnis
Trade – Der Handel
Refrigerator – Der Kühlschrank
Mister – Der Herr
Flashlight – Die Taschenlampe
Net – Das Internet
Sailor – Der Seemann
Attitude – Die Attitüde
Guilt – Die Schuld
Crying – Das Weinen
Sip – Die Sip
Travel – Die Reise
Cookie – Der Keks
Escape – Die Flucht
Instruction – Die Anleitung
Fabric – Das Gewebe
Marble – Der Marmor
Glimpse – Der Blick
Dusk – Die Dämmerung
Cottage – Die Hütte
Monkey – Der Affe
Makeup – Das Makeup
Doc – Die Doc
Blouse – Die Bluse
Rhythm – Der Rhythmus
Steam – Der Dampf
Phrase – Der Satz
Nut – Die Mutter
Pencil – Der Bleistift
Cook – Der Koch
Flag – Die Flagge
Coach – Der Trainer
Swing – Die Schaukel
Speaker – Der Lautsprecher
Bolt – Der Bolzen
Fat – Das Fett
Rug – Der Teppich
Knock – Die Klopf
Spell – Der Zauber
Taxi – Das Taxi
Round – Die Runde
Straw – Der Strohhalm
Hatch – Die Luke
Fork – Die Gabel
Evil – Das Böse
Maid – Das Dienstmädchen
Relative – Die Relative
Witch – Die Hexe
Courtyard – Der Hof
Sensation – Die Sensation
Bubble – Die Blase
Reader – Der Leser
Curl – Die Locke
Pie – Der Kuchen
Jet – Der Strahl
Shift – Die Verschiebung
Union – Die Union
Teenager – Der Teenager
Plain – Die Ebene
Waitress – Die Kellnerin
Reply – Die Antwort
Rumor – Das Gerücht
Gravity – Die Schwerkraft
Shelter – Die Zuflucht
Adventure – Das Abenteuer
Lion – Der Löwe
Spine – Die Wirbelsäule
Confidence – Das Vertrauen
Depth – Die Tiefe
Reach – Die Reichweite
Hammer – Der Hammer
Bible – Die Bibel
Contract – Der Vertrag
Wallet – Der Geldbeutel
Jungle – Der Dschungel
Factory – Die Fabrik
Indian – Die Indische
Balcony – Der Balkon
Rice – Der Reis
Knot – Der Knoten
Cord – Die Schnur
Colleague – Der Kollege
Intention – Die Absicht
Stare – Die Stare
Motel – Das Motel
Attorney – Der Anwalt
Darling – Der Liebling
Discussion – Die Diskussion
Atmosphere – Atmosphäre
Performance – Die Leistung
Tension – Die Spannung
Text – Der Text
Strand – Der Strang
Noon – Die Mittags
Vein – Die Vene
Expert – Der Experte
Gang – Die Gruppe
Policeman – Der Polizist
Cancer – Der Krebs
Fox – Der Fuchs
Divorce – Die Scheidung
Pulse – Die Impuls
Absence – Die Abwesenheit
Violence – Die Gewalt
Humor – Der Humor
Stool – Der Stuhl
Gravel – Der Kies
Treasure – Der Schatz
Butter – Die Butter
Switch – Der Schalter
Cigar – Die Zigarre
Canvas – Die Leinwand
Happiness – Die Fröhlichkeit
Guide – Der Führer
Pin – Der Stift
Actor – Der Schauspieler
Whole – Das Ganze
Arrangement – Die Vereinbarung
Brown – Die Braune
Host – Der Gastgeber
Ribbon – Das Farbband
Scarf – Der Schal
Scale – Die Skala
Proof – Der Beweis
Arrow – Der Pfeil
Temperature – Die Temperatur
Technology – Die Technologie
Permission – Die Erlaubnis
Location – Der Ort
Claw – Die Klaue
Cowboy – Der Cowboy
Agency – Die Agentur
Construction – Die Konstruktion
Hunting – Das Jagd
Vegetable – Das Gemüse
Tin – Die Dose
Helicopter – Der Hubschrauber
Trap – Die Falle
Pat – Das Pat
Gap – Die Lücke
Pet – Das Haustier
Education – Die Bildung
Shopping – Das Einkaufen
Shed – Der Schuppen
Agreement – Die Vereinbarung
Soil – Die Erde
Duke – Der Herzog
Shotgun – Die Schrotflinte
Notion – Die Vorstellung
Rear – Es Gibt
Ceremony – Die Zeremonie
Spoon – Der Löffel
Tub – Die Wanne
Clue – Der Schlüssel
Iris – Die Iris
Incident – Der Vorfall
Crash – Der Absturz
Journal – Das Tagebuch
Access – Die Zugriffs
Brass – Erz
Mommy – Die Mama
Sidebar – Die Seitenleiste
Sheep – Das Schaf
Engineer – Der Ingenieur
Hull – Der Rumpf
Odor – Der Geruch
Appointment – Der Termin
Invitation – Die Einladung
Rag – Die Lappen
Good – Das Gute
Dude – Der Kumpel
Treatment – Die Behandlung
Wisdom – Die Weisheit
Prize – Der Preis
Element – Das Element
Giant – Der Gigant
Napkin – Die Serviette
Laundry – Die Wäsche
Option – Die Option
Rack – Das Regal
Request – Die Anforderung
Jail – Das Gefängnis
Grandpa – Der Opa
Ranch – Die Ranch
Dot – Der Punkt
Script – Das Skript
Mall – Die Einkaufshalle
Ford – Der Ford
Exercise – Die Übung
Widow – Die Witwe
Crow – Die Krähe
Thread – Der Faden
Suicide – Die Selbstmord
Notice – Die Notiz
Sunset – Der Sonnenuntergang
Gallery – Die Gallerie
Vessel – Das Schiff
Thunder – Der Donner
Soap – Die Seife
Whiskey – Der Whisky
Female – Das Weibchen
Mayor – Der Bürgermeister
Stroke – Der Hub
Click – Der Klick
Reputation – Der Ruf
Miller – Der Müller
Council – Der Rat
Schedule – Der Stundenplan
Cemetery – Der Friedhof
Struggle – Der Kampf
Instinct – Der Instinkt
Calm – Die Ruhe
Employee – Der Arbeitnehmer
Nest – Das Nest
Limit – Das Limit
German – Der Deutsche
Monk – Der Mönch
Worm – Der Wurm
Document – Das Dokument
Sadness – Die Traurigkeit
Hut – Die Hütte
Lifetime – Die Lebensdauer
Dancer – Die Tänzerin
Insurance – Die Versicherung
Difficulty – Die Schwierigkeit
Mattress – Die Matratze
Male – Der Mann
Clinic – Die Klinik
Ad – Die Ad
Mug – Der Becher
Kit – Das Kit
Communication – Die Kommunikation
Disaster – Das Unglück
Tile – Die Fliese
Receiver – Der Empfänger
Roar – Das Gebrüll
Troop – Die Truppe
Coffin – Der Sarg
Friendship – Die Freundschaft
Investigation – Die Ermittlung
Sale – Der Verkauf
Goal – Das Ziel
Ambulance – Der Krankenwagen
Moonlight – Das Mondlicht
Ward – The Ward
Trousers – Die Hosen
Wool – Die Wolle
Mac – Die Mac
Minister – Der Minister
Entry – Der Eintritt
Thief – Der Dieb
Briefcase – Die Aktentasche
Pity – Das Mitleid
Fingertip – Die Finger
Navy – Die Marine
Insect – Das Insekt
Velvet – The Velvet
Bee – Die Biene
Cane – Der Stock
Gene – Das Gen
Salad – Der Salat
Windshield – Die Windschutzscheibe
Outfit – Das Outfit
Shuttle – Der Shuttle
Shout – Der Schrei
Fury – Die Wut
Challenge – Die Herausforderung
Satisfaction – Die Zufriedenheit
Motor – Der Motor
Product – Das Produkt
Weed – Das Unkraut
Stretch – Die Strecke
Gym – Das Fitnesscenter
Capital – Das Kapital
Rim – Der Rand
Paw – Die Pfote
Fort – Die Festung
Cost – Die Kosten
Poster – Das Plakat
Vampire – Der Vampir
Shaft – Die Welle
Identity – Die Identität
Pavement – Der Bürgersteig
Asshole – Das Arschloch
Strap – Der Gurt
Parlor – Das Wohnzimmer
Harbor – Der Hafen
Example – Das Beispiel
Web – Das Netz
Golf – Der Golf
Crap – Den Mist
Delight – Die Freude
Quilt – Die Decke
Tax – Die Steuer
Fold – Die Falte
Portrait – Das Porträt
Tissue – Das Gewebe
Belief – Der Glaube
Costume – Das Kostüm
Measure – Das Maß
Carriage – Der Wagen
Guitar – Die Gitarre
Knight – Der Ritter
Rank – Der Rang
Major – Der Bürgermeister
Fountain – Der Brunnen
Stall – Der Stall
Load – Die Ladung
Spark – Der Funke
Waste – Der Müll
Champagne – Der Champagner
District – Das Viertel
Protection – Der Schutz
Judgment – Das Urteil
Sympathy – Die Sympathie
Violet – Das Violett
Impact – Der Aufprall
Disappointment – Die Enttäuschung
Drinking – Das Trink
Consciousness – Das Bewusstsein
Handkerchief – Das Taschentuch
Dancing – Das Tanzen
Perfume – Das Parfüm
Network – Das Netzwerk
Claim – Der Anspruch
Nun – Die Nonne
Crown – Die Krone
Railing – Das Geländer
License – Die Lizenz
Mercy – Die Barmherzigkeit
Balloon – Der Ballon
Chaos – Das Chaos
Fever – Das Fieber
Locker – Das Schließfach
Session – Die Sitzung
Burst – Die Burst
Peak – Der Spitzer
Drum – Die Trommel
Focus – Der Fokus
Frog – Der Frosch
Benefit – Der Vorteil
Remark – Die Bemerkung
Tide – Die Gezeiten
Suspicion – Der Verdacht
Jeep – Der Jeep
Worry – Die Sorge
Literature – Die Literatur
Archer – Der Bogenschütze
Household – Der Haushalt
Powder – Das Pulver
Shepherd – Der Hirte
Lens – Die Linse
Favorite – Der Favorit
Madame – Die Madame
Mansion – Die Villa
Boom – Der Boom
Lace – Die Spitze
Review – Die Überprüfung
Reception – Die Rezeption
Scrap – Der Schrott
Bead – Der Wulst
Glare – Die Blendung
Flow – Die Strömung
Cafe – Das Cafe
Status – Der Status
Pounding – Das Pochen
Rocket – Die Rakete
Canyon – Die Schlucht
Sorrow – Die Trauer
Spider – Die Spinne
Blast – Die Explosion
Personality – Die Persönlichkeit
Campus – Der Campus
Curse – Der Fluch
Staircase – Das Treppenhaus
Urge – Der Drang
Frustration – Die Frustration
Pump – Die Pumpe
Ease – Die Leichtigkeit
Count – Die Zählung
Solution – Die Lösung
Jewelry – Der Schmuck
Siren – Die Sirene
Hit – Der Schlag
Tradition – Die Tradition
Curb – Das Leer
Variety – Die Vielfalt
Pirate – Der Pirat
Description – Die Beschreibung
Dear – Der Liebe
Anxiety – Die Angst
Pitch – Die Tonhöhe
Pizza – Die Pizza
Elephant – Der Elefant
Politics – Die Politik
Tennis – Der Tennis
Hunger – Der Hunger
Genius – Das Genie
Goat – Die Ziege
Victory – Der Sieg
Combination – Die Kombination
Affiliation – Die Zugehörigkeit
Momma – Das Momma
Cape – Der Umhang
Headlight – Der Scheinwerfer
Governor – Der Gouverneur
Oxygen – Die Sauerstoff
Bishop – Der Bischof
Bundle – Das Bündel
Development – Die Entwicklung
Fingernail – Der Fingernagel
Score – Die Punktzahl
Mate – Der Steuermann
Rider – Der Fahrer
Orbit – Die Umlaufbahn
Vine – Der Weinstock
Suite – Die Suite
Bartender – Der Barkeeper
Coke – Der Koks
Tune – Die Melodie
Glory – Die Herrlichkeit
Rabbi – Der Rabbi
Surgery – Die Operation
Cattle – Das Vieh
Ritual – Das Ritual
Greeting – Die Begrüßung
Slice – Die Scheibe
Homer – Die Homer
Fireplace – Der Kamin
Jersey – Das Trikot
Media – Die Medien
Pop – Die Pop
Cargo – Die Fracht
Inn – Das Gasthaus
Deputy – Der Stellvertretende
Despair – Die Verzweiflung
Territory – Das Territorium
Punch – Der Schlag
Jazz – Die Jazz
Hug – Die Umarmung
Whistle – Die Pfeife
Humanity – Die Menschlichkeit
Craft – Das Handwerk
Daylight – Das Tageslicht
Worth – Der Wert
Slip – Der Slip
Armor – Die Rüstung
Backpack – Der Rucksack
Suggestion – Der Vorschlag
Den – Die Höhle
Symbol – Das Symbol
Colony – Die Kolonie
Conclusion – Das Fazit
Nostril – Das Nasenloch
Spear – Der Speer
Impulse – Der Impuls
Tomato – Die Tomate
Calf – Das Kalb
Autumn – Der Herbst
Discovery – Der Fund
Classroom – Das Klassenzimmer
Delivery – Die Lieferung
Spray – Das Spray
Liquid – Die Flüssigkeit
Fuel – Die Kraftstoff
Underwear – Die Unterwäsche
Dome – Die Kuppel
Population – Die Bevölkerung
Affection – Die Neigung
Religion – Die Religion
Singer – Der Sänger
Attendant – Der Begleiter
Illusion – Die Illusion
Link – Der Link
Lounge – Das Wohnzimmer
Interior – Der Innenraum
Shrug – Die Achselzucken
Zone – Die Zone
Standard – Der Standard
Coal – Die Kohlen
Chase – Die Jagd
Lump – Der Klumpen
Charm – Der Charm
Legend – Die Legende
Consequence – Die Konsequenz
Observation – Die Beobachtung
Bicycle – Das Fahrrad
Harm – Der Schaden
Pay – Die Zahlung
Prospect – Das Prospekt
Subway – Die UBahn
Sample – Das Muster
Cherry – Die Kirsche
Dealer – Der Händler
Assignment – Die Zuordnung
Hurry – Die Eile
Mistress – Die Geliebte
Mound – Der Hügel
Nonsense – Der Unsinn
Committee – Das Komitee
Echo – Das Echo
Slack – Der Durchhang
Decker – Die Decker
Warehouse – Das Warenhaus
Bout – Der Kampf
Toast – Der Toast
Facility – Die Einrichtung
Basketball – Der Basketball
Mustache – Der Schnurrbart
Senator – Der Senator
Share – Das Teilen
Eyelid – Das Augenlid
Enthusiasm – Die Begeisterung
Chunk – Die Chunk
Turtle – Die Schildkröte
Alcohol – Der Alkohol
Gum – Die Gummi
Turkey – Der Truthahn
Preacher – Der Prediger
Possession – Der Besitz
Dolly – Der Dolly
Linen – Das Leinen
Apology – Die Entschuldigung
Lecture – Der Vortrag
Boulder – Der Stein
Heap – Der Heap
Photographer – Der Fotograf
Brake – Die Bremse
Demand – Die Nachfrage
Apron – Die Schürze
Cloak – Der Mantel
Jury – Die Jury
Hearing – Die Anhörung
Gray – Das Graue
Crate – Die Kiste
Method – Die Methode
Reference – Die Referenz
Disgust – Der Ekel
Liquor – Die Flotte
Lipstick – Der Lippenstift
Core – Der Kern
Individual – Der Einzelne
Container – Der Container
Whore – Die Hure
Infant – Das Kleinkind
Sunglasses – Die Sonnenbrille
Hose – Der Schlauch
Concert – Das Konzert
Bullshit – Das Bullshit
Railroad – Die Eisenbahn
Parade – Die Parade
Compartment – Das Fach
Resident – Der Bewohner
Oven – Der Backofen
Technician – Der Techniker
Procedure – Das Verfahren
Fighter – Der Kämpfer
Grain – Das Korn
Picnic – Das Picknick
Tribe – Der Stamm
Bud – Die Knospe
Meadow – Die Wiese
Public – Die Öffentlichkeit
Poison – Das Gift
Buffalo – Der Büffel
Region – Die Region
Production – Die Produktion
Running – Das Rennen
Loop – Die Schleife
Sleeping – Der Schlaf
Soda – Die Soda
Owl – Die Eule
Menu – Das Menü
Kick – Der Kick
Ruin – Die Ruine
Ramp – Die Rampe
Streak – Der Streifen
Forearm – Unterarm
Bureau – Das Büro
Knuckle – Der Achsschenkel
Goose – Die Gans
Advance – Der Vormarsch
Fairy – Die Fee
Illness – Die Krankheit
Squad – Die Mannschaft
Official – Das Offizielle
Brand – Die Marke
Organ – Die Orgel
Butterfly – Der Schmetterling
Empire – Das Reich
Profile – Das Profil
Liberty – Die Freiheit
Disbelief – Der Unglaube
Grove – Der Hain
Shield – Das Schild
Saddle – Der Sattel
Odds – Die Chancen
Cluster – Die Cluster
Satellite – Der Satellit
Trigger – Der Abzug
Puppy – Der Welpe
Waiting – Die Warte
Bulb – Die Glühbirne
Dresser – Die Kommode
Patrol – Die Patrouille
Eagle – Der Adler
Privacy – Der Privatsphäre
Fluid – Das Fluid
Herd – Die Herde
Headache – Der Kopfschmerz
Amusement – Der Vergnügungspark
Wheelchair – Der Rollstuhl
Policy – Die Richtlinie
Belle – Das Belle
Tobacco – Die Tabak
Setting – Die Einstellung
Tattoo – Die Tätowierung
Burden – Die Last
Merchant – Der Händler
Slide – Die Rutsche
Stain – Der Fleck
Eating – Das Essen
Bond – Die Bindung
Swimming – Das Schwimmen
Foundation – Die Grundlage
Injury – Die Verletzung
League – Die Liga
Battery – Die Batterie
Umbrella – Der Regenschirm
Emperor – Der Kaiser
Pier – Der Pier
Tap – Der Wasserhahn
Wit – Der Witz
Cutter – Der Cutter
Attic – Der Dachboden
Tiger – Der Tiger
Pal – Die Pal
Ancestor – Der Vorfahr
Concentration – Die Konzentration
Mount – Der Berg
Expense – Der Aufwand
Blessing – Der Segen
Leave – Der Urlaub
Ledge – Die Leiste
Torch – Die Fackel
Ink – Die Tinten
Plot – Die Handlung
Rent – Die Miete
Mule – Das Maultier
Arch – Der Bogen
Environment – Die Umgebung
Frown – Das Stirnrunzeln
Inspector – Der Inspektor
Midst – Die Mitten
Embarrassment – Die Verlegenheit
Complaint – Die Beschwerde
Portion – Die Portion
Chuck – Das Spannfutter
Clearing – Die Clearing
Crisis – Die Krise
Necklace – Die Halskette
Lantern – Die Laterne
Wealth – Der Reichtum
Murderer – Der Mörder
Civilization – Die Zivilisation
Concept – Das Konzept
Lamb – Das Lamm
Stride – Die Schritt
Cuff – Die Manschette
Virgin – Die Jungfrau
Squirrel – Das Eichhörnchen
Babe – Das Kind
Starling – Der Star
Depression – Die Depression
Storage – Das Speicher
Altar – Der Altar
Tragedy – Die Tragödie
Resource – Die Ressource
Traveler – Der Reisende
Trust – Das Vertrauen
Arc – Die Bogen
Kingdom – Das Königreich
Jewel – Das Juwel
Musician – Der Musiker
Airplane – Das Flugzeug
Junk – Die Junk
Sunshine – Der Sonnenschein
Lad – Der Knabe
Elf – Der Elf
Protest – Der Protest
Hunt – Die Jagd
Executive – Die Exekutive
Diary – Das Tagebuch
Aspect – Das Aspekt
Dial – Das Zifferblatt
Slipper – Der Hausschuh
Actress – Die Schauspielerin
Shooting – Das Shooting
Earring – Der Ohrring
Ant – Die Ameise
Patty – Die Patty
Sauce – Die Sauce
Missile – Die Rakete
Intensity – Die Intensität
Ditch – Der Graben
Daisy – Das Gänseblümchen
Chapel – Die Kapelle
Swamp – Der Sumpf
Relation – Die Beziehung
Guess – Die Vermutung
Crane – Der Kran
Encounter – Die Begegnung
Sequence – Die Sequenz
Fragment – Das Fragment
Draft – Der Entwurf
Diner – Das Diner
Function – Die Funktion
Organization – Die Organisation
Skeleton – Das Skelett
Misery – Das Elend
Herb – Das Kraut
Stump – Der Stumpf
Stake – Der Einsatz
Puff – Die Puff
Creation – Die Kreation
Wake – Das Gefolge
Wizard – Der Zauberer
Mat – Die Matte
Seal – Die Dichtung
Twilight – Das Zwielicht
Grunt – Das Grunzen
Punishment – Die Strafe
Clan – Der Clan
Copper – Das Kupfer
Debris – Die Trümmer
Painter – Der Maler
Steering – Das Steuer
Math – Die Mathematik
Recognition – Die Erkennung
Temper – Die Stimmung
Regret – Das Bedauern
Destination – Das Ziel
Mill – Die Mühle
Error – Der Fehler
Romance – Die Romantik
Topic – Das Thema
Patio – Die Terrasse
Shovel – Die Schaufel
Pajamas – Die Schlafanzüge
EMail – Die Email
Pigeon – Die Taube
Dinosaur – Der Dinosaurier
Industry – Die Branche
Operator – Der Betreiber
Lift – Der Lift
Counselor – Der Ratgeber
Gathering – Die Versammlung
Principle – Das Prinzip
Drama – Das Drama
Chick – Das Küken
Chart – Das Diagramm
Campaign – Die Kampagne
Laurel – Der Lorbeer
Steak – Das Steak
Criminal – Der Kriminelle
Globe – Der Globus
Bruise – Der Bluterguss
Knob – Der Knopf
Killing – Das Töten
Sweetheart – Der Schatz
Opera – Die Oper
Frost – Der Frost
Nipple – Der Nippel
Reverend – Der Pfarrer
Haze – Die Trübung
Flood – Das Hochwasser
Carol – Das Weihnachtslied
Weakness – Die Schwäche
Cooking – Das Kochen
Butcher – Der Metzger
Cube – Der Würfel
Cellar – Der Keller
Hollow – Der Hohl
Bump – Der Höcker
Halt – Der Halt
Hay – Das Heu
Bark – Die Rinde
Survival – Die Überlebens
Bunk – Die Etagen
Bend – Die Biegung
Approval – Die Freigabe
Division – Der Unternehmensbereich
Cocktail – Der Cocktail
Contest – Der Wettbewerb
Paradise – Das Paradies
Razor – Das Rasiermesser
Catch – Der Fang
Blossom – Die Blüte
Puddle – Die Pfütze
Electricity – Der Strom
Onion – Die Zwiebel
Laser – Die Laser
Cushion – Das Kissen
Influence – Der Einfluss
Jump – Der Sprung
Cement – Der Zement
Amber – Die Gelbe
Goddess – Die Göttin
Shack – The Shack
Sales – Die Verkäufe
Drift – Die Drift
Fighting – Die Kämpfe
Braid – Das Geflecht
Theme – Das Thema
Dignity – Die Würde
Lemon – Die Zitrone
Clown – Der Clown
Assault – Der Angriff
Goggle – Die Brille
Destruction – Die Zerstörung
Exception – Die Ausnahme
Peach – Der Pfirsich
Wash – Die Wasch
Release – Die Befreiung
Spy – Der Spion
Tag – Die Tag
Bra – Der Bh
Debt – Die Schuld
Terrace – Die Terrasse
Remains – Die Überbleibsel
Logic – Die Logik
Joint – Der Joint
Pitcher – Der Krug
Perspective – Die Perspektive
Crop – Die Ernte
Graduate – Der Diplom
Chorus – Der Chor
Survivor – Der Überlebende
Payment – Die Bezahlung
Bet – Die Wette
Revenge – Die Rache
Plaza – Der Platz
Elder – Der Ältere
Ginger – Der Ingwer
Surgeon – Der Chirurg
Dash – Der Bindestrich
Sandal – Die Sandale
Hatred – Der Hass
Departure – Die Abfahrt
Outline – Der Umriss
Raven – Der Rabe
Runner – Der Läufer
Anticipation – Die Vorfreude
Translation – Die Übersetzung
Headquarters – Das Hauptquartier
Celebration – Feier
Agony – Die Qual
Sneakers – Die Turnschuhe
Terminal – Das Terminal
Expectation – Die Erwartung
Pasture – Die Weide
Console – Die Konsole
Strike – Der Streik
Rescue – Die Rettung
Badge – Das Abzeichen
Fund – Der Fonds
Try – Der Versuch
Foyer – Das Foyer
Pastor – Der Pastor
Embrace – Die Umarmung
Puzzle – Das Puzzle
Canal – Der Kanal
Charity – Die Wohlfahrt
Principal – Der Direktor
Applause – Der Applaus
Philosophy – Die Philosophie
Trench – Der Graben
Up – Die Bis
Nephew – Der Neffe
Essay – Der Aufsatz
Repair – Die Reparatur
Mix – Der Mix
Mob – Der Mob
Barrier – Die Barriere
Disk – Die Platte
Goodness – Die Güte
Scout – Der Scout
Importance – Die Wichtigkeit
Destiny – Das Schicksal
Aid – Die Beihilfen
Microphone – Das Mikrofon
Label – Das Etikett
Pepper – Der Pfeffer
Coyote – Der Kojote
Teaching – Das Lehren
Burn – Der Brennvorgang
Vest – Die Weste
Pony – Das Pony
Donkey – Der Esel
Cycle – Der Kreislauf
Gasp – Das Keuchen
Irony – Die Ironie
Award – Die Auszeichnung
Grape – Die Traube
Hesitation – Das Zögern
Tavern – Die Taverne
Chore – Die Lästige Pflicht
Sphere – Die Kugel
Sail – Das Segel
Silhouette – Die Silhouette
Institute – Das Institut
Liar – Der Lügner
Technique – Die Technik
Index – Der Index
Plank – Das Brett
Jerk – Der Ruck
Growth – Das Wachstum
Stocking – Der Strumpf
Blackness – Die Schwärze
Teen – Der Teenager
Bracelet – Das Armband
Jelly – Gelee
Diet – Die Diät
Beef – Das Fleisch
Concrete – Der Beton
Contrast – Der Kontrast
Banner – Das Banner
Resistance – Der Widerstand
Stay – Der Aufenthalt
Posture – Die Haltung
Vodka – Der Wodka
Album – Das Album
Era – Die Ära
Acquaintance – Die Bekanntschaft
Revolution – Die Revolution
Nap – Der Nap
Veil – Der Schleier
Spectacle – Das Schauspiel
Competition – Der Wettbewerb
Scalp – Die Kopfhaut
Holly – Die Stechpalme
Winner – Der Gewinner
Appetite – Der Appetit
Ivy – Der Efeu
Cue – Der Cue
Strain – Der Stamm
Niece – Die Nichte
Galaxy – Die Galaxie
Bedside – Die Nacht
Madness – Die Verrücktheit
Baker – Der Bäcker
Virus – Das Virus
Suffering – Das Leiden
Slot – Der Schlitz
Folder – Der Ordner
Confession – Das Bekenntnis
Porter – Der Gepäckträger
Dessert – Das Dessert
Dump – Die Müllhalde
Packet – Das Paket
Profit – Der Gewinn
Grandchild – Der Enkel
Gossip – Der Tratsch
Mare – Die Stute
Dna – Die Dna
Torso – Der Rumpf
Broom – Der Besen
Hoof – Der Huf
Sensor – Der Sensor
Peasant – Der Bauer
Scholar – Der Gelehrte
Therapy – Die Therapie
Peanut – Die Erdnuss
Headline – Die Schlagzeile
Bacon – Der Speck
Stern – Das Heck
Violin – Die Geige
Plague – Die Pest
Blur – Die Unschärfe
Meantime – Die Zwischenzeit
Deacon – Der Diakon
Lance – Die Lanze
Arrest – Die Festnahme
Banana – Die Banane
Gin – Der Gin
Willow – Die Weide
Shark – Der Hai
Preparation – Die Vorbereitung
Scratch – Die Kratz
Dressing – Der Verband
Signature – Die Unterschrift
Admiral – Der Admiral
Analysis – Die Analyse
Rainbow – Der Regenbogen
Lizard – Die Eidechse
Dwarf – Der Zwerg
Stress – Der Stress
Homework – Die Hausaufgabe
Mixture – Die Mischung
Verse – Der Vers
Conviction – Die Überzeugung
Rover – Der Rover
Wren – Der Zaunkönig
Compound – Die Verbindung
Expedition – Die Expedition
Reward – Die Belohnung
Pillar – Die Säulen
Jam – Die Marmelade
Brandy – Der Schnaps
Residence – Die Residenz
Baron – Der Baron
Enterprise – Das Unternehmen
Complex – Der Komplex
Candidate – Der Kandidat
Triumph – Der Triumph
Twist – Die Wendung
Sketch – Die Skizze
Register – Das Register
Heartbeat – Der Herzschlag
Cafeteria – Die Cafeteria
Fee – Die Gebühr
Hillside – Die Hang
Maze – Das Labyrinth
Fisherman – Der Fischer
Hum – Das Brummen
Kitten – Das Kätzchen
Dread – The Dread
Substance – Die Substanz
Melody – Die Melodie
Bang – Der Knall
Dagger – Der Dolch
Intent – Die Absicht
Con – Das Con
Loneliness – Die Einsamkeit
Motorcycle – Das Motorrad
Amazement – Das Staunen
Peer – Die Peer
Tech – Die Tech
Insult – Die Beleidigung
Capacity – Die Kapazität
Awe – Die Ehrfurcht
Chili – Die Chili
Lodge – Die Lodge
Clip – Der Clip
Limo – Die Limousine
Mosquito – Die Mücke
Dice – Der Würfel
Shake – Der Shake
Feast – Das Festmahl
Casino – Das Casino
Pea – Die Erbse
Murmur – Das Murmeln
Conflict – Der Konflikt
Stem – Der Stamm
Comrade – Der Genosse
Flock – Die Herde
Sob – Sob
Pregnancy – Die Schwangerschaft
Suspect – Der Verdächtige
Coincidence – Das Zusammentreffen
Ranger – Der Waldläufer
Cartoon – Die Karikatur
Roommate – Der Mitbewohner
Kindness – Die Freundlichkeit
Cruiser – Der Kreuzer
Slab – Die Bramme
Conscience – Das Gewissen
Cheer – Die Cheer
Cone – Der Konus
Circuit – Die Schaltung
Ivory – Das Elfenbein
Carpenter – Der Zimmermann
Realm – Das Reich
Bum – Der Penner
Donna – Die Donna
Reservation – Die Reservierung
Entertainment – Die Unterhaltung
Crab – Die Krabbe
Groan – Das Stöhnen
Academy – Die Akademie
Longing – Die Sehnsucht
Kip – Die Kip
Drill – Der Bohrer
Luggage – Das Gepäck
Canopy – Der Baldachin
Thrill – Der Nervenkitzel
Virtue – Die Tugend
Marsh – Der Sumpf
Chimney – Der Schornstein
Anchor – Die Anker
Harmony – Die Harmonie
Maple – Das Ahorn
Bunny – Das Kaninchen
Mode – Der Modus
Throne – Der Thron
Application – Der Antrag
Physics – Die Physik
Neon – Das Neon
Airlock – Die Luftschleuse
Fatigue – Die Ermüdungs
Thanksgiving – Die Danksagung
Manuscript – Das Manuskript
Basis – Die Basis
Memorial – Das Denkmal
Cupboard – Der Schrank
Leap – Der Sprung
Japanese – Die Japaner
Engineering – Das Engineering
Left – Die Linke
Ache – Der Schmerz
Bronze – Die Bronze
Association – Die Assoziation
Fleet – Die Flotte
Marker – Der Marker
Prey – Die Beute
Dove – Die Taube
Grasp – Der Griff
Episode – Die Episode
Origin – Der Ursprung
Vacuum – Das Vakuum
Cathedral – Die Kathedrale
Management – Das Management
Down – Die Nach Unten
Continent – Der Kontinent
Dickens – Zum Teufel
Volunteer – Die Freiwillige
Soccer – Fußball
Hem – Der Saum
Mention – Die Erwähnung
Lust – Die Lust
Giggle – Die Kichern
Classmate – Die Klassenkameraden
Cleaning – Die Reinigung
Receptionist – Der Rezeptionist
Caller – Der Anrufer
Pursuit – Das Streben
Contempt – Die Verachtung
Sacrifice – Das Opfer
Grandparent – Die Großeltern
Threshold – Der Grenzbereich
Deed – Die Tat
Countryside – Die Landschaft
Artifact – Das Artefakt
Wrinkle – Die Falten
Magician – Der Magier
Pang – Der Stich
Italian – Die Italienische
Eternity – Die Ewigkeit
Slate – Der Schiefer
Stairwell – Das Treppenhaus
Announcement – Die Ankündigung
Motive – Das Motiv
Mechanic – Der Mechaniker
Ally – Der Verbündete
Vase – Die Vase
Salesman – Der Verkäufer
Therapist – Der Therapeut
Granny – Die Oma
Maverick – Der Außenseiter
Bandage – Die Bandage
Ham – Der Schinken
Carter – Der Fuhrmann
Investment – Die Investition
Appeal – Die Beschwerde
Innocence – Die Unschuld
Calendar – Der Kalender
Rooftop – Die Dach
Combat – Der Kampf
Revelation – Die Offenbarung
Pancake – Der Pfannkuchen
Asteroid – Der Asteroid
Postcard – Die Postkarte
Garment – Das Kleidungsstück
Determination – Die Bestimmung
Tractor – Der Traktor
Berry – Die Beere
Surroundings – Die Umgebung
Clump – Der Klumpen
Offense – Die Straftat
Introduction – Die Einleitung
Butler – Der Butler
Cough – Der Husten
Granite – Der Granit
Ambassador – Der Botschafter
Turning – Der Wende
Sitting – Die Sitzung
Compliment – Das Kompliment
Carton – Der Karton
Doorbell – Die Türklingel
Certainty – Die Gewissheit
Politician – Der Politiker
Gratitude – Die Dankbarkeit
Current – Die Jetzige
Gloom – Das Dunkel
Plaster – Der Putz
Settlement – Die Siedlung
Chop – Die Chop
Homicide – Die Mordkommission
Aluminum – Die Aluminium
Boulevard – Der Boulevard
Pupil – Der Schüler
Float – Der Schwimmer
Profession – Der Beruf
Retreat – Der Rückzug
Intersection – Der Schnittpunkt
Scheme – Die Regelung
Emptiness – Die Leere
Publisher – Der Verlag
Circus – Der Zirkus
Dimension – Die Abmessung
Zoo – Der Tierpark
Sickness – Die Krankheit
Messenger – Der Bote
Beau – Das Beau
Tangle – Das Gewirr
Personnel – Das Personal
Strategy – Die Strategie
Desperation – Die Verzweiflung
Businessman – Der Geschäftsmann
Pod – The Pod
Drain – Der Abfluss
Strawberry – Die Erdbeere
Anniversary – Der Jahrestag
Binoculars – Das Fernglas
Gulf – Die Kluft
Discipline – Die Disziplin
Hedge – Die Hecke
Moan – Das Stöhnen
Income – Das Einkommen
Myth – Der Mythos
Shutter – Der Verschluss
Raft – Das Floß
Physician – Der Arzt
Ambition – Der Ehrgeiz
Camel – Das Kamel
Beating – Das Schlagen
Acid – Die Säure
Cereal – Müsli
Basin – Das Becken
Nightgown – Das Nachthemd
Internet – Das Internet
Cockpit – Das Cockpit
Wreck – Das Wrack
Wig – Die Perücke
Rein – Darin
Recorder – Der Recorder
Pork – Das Schweinefleisch
Hound – Der Hund
Boundary – Die Grenze
Exam – Die Prüfung
Courtesy – Die Höflichkeit
Assistance – Die Hilfe
Cheekbone – Die Wangenknochen
Whip – Die Peitsche
Pilgrim – Der Pilger
Grease – Das Fett
Collapse – Der Kollaps
Faculty – Die Fakultät
Reminder – Die Erinnerung
Sage – Der Weise
Asphalt – Der Asphalt
Privilege – Das Privileg
Stairway – Das Treppenhaus
Maintenance – Die Wartung
Sweetie – Die Süße
Orchard – Der Obstgarten
Cot – Das Kinderbett
Pouch – Der Beutel
Lighter – Das Feuerzeug
Kitty – Die Katze
Formation – Die Formation
Snack – Die Snack
Talking – Das Reden
Op – Die Op
Shriek – Der Schrei
Sculpture – Die Skulptur
Chairman – Der Vorsitzende
Sum – Die Summe
Carrot – Die Karotte
Ripple – Die Welligkeit
Stripe – Der Streifen
Cavern – Die Höhle
Radar – Die Radar
Ponytail – Der Pferdeschwanz
Designer – Der Designer
Surge – Die Stoß
Heir – Der Erbe
Vault – Der Bunker
Sissy – Die Sissy
Scotch – Die Schotten
Stillness – Die Stille
Tunic – Die Tunika
Think – Der Think
Penis – Der Penis
Native – Der Einheimische
Lovemaking – Das Liebesspiel
Aide – Der Adjutant
Bulk – Der Großteil
Poker – Die Poker
Lime – Der Kalk
Surveillance – Das Überwachungs
Assembly – Die Versammlung
Grandson – Der Enkel
Chopper – Der Chopper
Carrier – Der Träger
Engagement – Die Verlobung
Kin – Das Kin
Mum – Die Mama
Lighting – Die Beleuchtung
Fit – Die Passform
Pull – Die Pull
Verge – The Verge
Farmhouse – Das Bauernhaus
Wait – Das Warten
Assassin – Der Attentäter
Foam – Der Schaum
Tug – Der Schlepper
Journalist – Der Journalist
Recording – Die Aufnahme
Cure – Die Heilung
Descent – Der Abstieg
Ringing – Das Klingeln
Scissors – Die Schere
Twig – Der Zweig
Resort – Der Urlaubsort
Guardian – Der Beschützer
Opponent – Der Gegner
Chef – Der Küchenchef
Wheat – Der Weizen
Hurricane – Der Hurrikan
Playground – Der Spielplatz
Mushroom – Der Pilz
Keyboard – Die Tastatur
Cedar – Die Zeder
Crest – Das Wappen
Jasmine – Der Jasmin
Armchair – Der Sessel
Attraction – Die Attraktion
Blind – Blinde
Cylinder – Zylinder
Swallow – Die Schwalbe
Celebrity – Die Berühmtheit
Wilderness – Die Wildnis
Triangle – Das Dreieck
Stench – Der Gestank
Laboratory – Das Labor
Array – Das Array
Valentine – The Valentine
Retirement – Das Renten
Ski – Der Ski
Edition – Die Ausgabe
Supervisor – Der Supervisor
Expanse – Die Weite
Ending – Das Ende
Moss – Das Moos
Gale – Der Sturm
Loyalty – Die Treue
Lavender – Der Lavendel
Pardon – Die Begnadigung
Ashtray – Der Aschenbecher
Shard – Die Scherbe
Corporation – Das Unternehmen
Distraction – Die Ablenkung
Majesty – Die Majestät
Pyramid – Die Pyramide
Fame – Der Ruhm
Graduation – Der Schulabschluss
Distress – Die Not
Mage – Der Magier
Independence – Die Unabhängigkeit
Crush – Der Schwarm
Chuckle – Das Lachen
Dime – Die Dime
Aim – Das Ziel
Gust – Die Böen
Russian – Der Russe
Treat – Der Festlichkeit
Foreigner – Der Ausländer
Salary – Das Gehalt
Scope – Der Anwendungsbereich
Rebel – Der Rebell
Thug – Der Schläger
Tomb – Das Grab
Fridge – Der Kühlschrank
Socket – Die Steckdose
Dose – Die Dosis
Election – Die Wahl
Refugee – Der Flüchtling
Phase – Die Phase
Pumpkin – Der Kürbis
Thorn – Der Dorn
Hide – Die Haut
Sausage – Die Wurst
Dig – Die Dig
Tan – Der Tan
Loan – Das Darlehen
Spike – Der Dorn
Crumb – Die Krume
Wax – Das Wachs
Growl – Das Knurren
Rental – Die Vermietung
Feed – Das Futter
Escort – Die Eskorte
Astonishment – Das Erstaunen
Flora – Die Flora
Festival – Das Fest
Debate – Die Debatte
Critic – Der Kritiker
Cast – Die Besetzung
Bloom – Die Blüte
Loft – Das Loft
Commission – Die Kommission
Flicker – Das Flimmern
Economy – Die Wirtschaft
Radiation – Die Strahlung
Bodyguard – Der Leibwächter
Realization – Die Umsetzung
Crater – Der Krater
Voyage – Die Reise
Congress – Das Kongress
Vote – Die Wahl
Proposal – Der Antrag
Fry – Der Braten
Shiver – Das Zittern
Obligation – Die Verpflichtung
Loser – Der Verlierer
Instructor – Der Lehrer
Wink – Die Zuzwinkern
Pebble – Die Kies
Necessity – Die Notwendigkeit
Workshop – Der Workshop
Sunrise – Der Sonnenaufgang
Exhaustion – Die Erschöpfung
Cubicle – Die Zelle
Double – Der Doppelgänger
Perimeter – Der Umfang
Comb – Der Kamm
Finish – Das Ende
Purchase – Der Kauf
Interval – Das Intervall
Splash – Der Spritz
Convention – Die Konvention
Awareness – Das Bewusstsein
Pose – Die Pose
Cradle – Die Wiege
Ram – Der Stößel
Gentry – Der Adel
Seam – Die Naht
Associate – Das Assoziierte Unternehmen
Pane – Die Scheibe
Punk – Der Punk
Remnant – Der Überrest
Cracker – Der Cracker
Bluff – Der Bluff
Dune – Die Düne
Dentist – Der Zahnarzt
Refuge – Die Zuflucht
Satin – Die Satin
Spread – Die Verbreitung
Entity – Das Unternehmen
Mailbox – Das Postfach
Annoyance – Der Ärger
Hiss – Das Zischen
Local – Das Lokal
Thud – Der Bums
Dismay – Die Bestürzung
Flour – Das Mehl
Freak – Der Freak
Haircut – Der Haarschnitt
Sweet – Die Süße
Orphan – Die Waise
Chess – Das Schach
Petal – Die Blütenblatt
Paperwork – Die Schreibarbeit
Psychiatrist – Der Psychiater
Singing – Der Gesang
Interrupt – Das Interrupt
Examination – Die Untersuchung
Admiration – Die Bewunderung
Freezer – Das Gefrier
Illustration – Die Illustration
Stew – Der Eintopf
Investigator – Der Ermittler
Suburb – Der Vorort
Biscuit – Der Keks
Holster – Das Holster
Factor – Der Faktor
Intimacy – Die Intimität
Lash – Die Peitsche
Saving – Die Einsparung
Software – Die Software
Hen – Die Henne
Birch – Die Birke
Inquiry – Die Untersuchung
Nursery – Der Kindergarten
Transport – Der Transport
Extent – Das Ausmaß
Definition – Die Definition
Monument – Das Monument
Plum – Die Pflaume
Void – Das Nichts
Delay – Die Verzögerung
Inspection – Die Inspektion
Essence – Die Essenz
Cannon – Die Kanone
Fringe – Die Fransen
Stereo – Die Stereo
Fella – Die Fella
Praise – Das Lob
Penguin – Der Pinguin
Torture – Die Folter
Stamp – Die Briefmarke
Particle – Die Partikel
Translator – Der Übersetzer
Easter – Ostern
Freeze – Das Einfrieren
Pew – Die Pew
Wad – Der Pfropfen
Panties – Das Höschen
Consideration – Die Gegenleistung
Spit – Der Spieß
Cooler – Der Kühler
Grill – Der Grill
Jug – Der Krug
Nickname – Der Spitzname
Revolver – Der Revolver
Machinery – Die Maschinen
Madam – Die Damen Und Herren
Pike – Der Hecht
Terrorist – Der Terrorist
Laptop – Der Laptop
Offering – Das Angebot
Beak – Der Schnabel
Institution – Die Institution
Comparison – Der Vergleich
Maker – Der Macher
Insight – Die Einsicht
Sibling – Die Geschwister
Wardrobe – Der Kleiderschrank
Flap – Die Klappe
Sole – Der Einzige
Compassion – Das Mitgefühl
Ego – Das Ego
Antenna – Die Antennen
Cricket – Die Grille
Troll – Der Troll
Bookstore – Der Bücherladen
Coming – Die Ankunft
Objection – Der Einwand
Holder – Der Halter
Backseat – Rücksitz
Ignorance – Die Unwissenheit
Budget – Das Budget
Aircraft – Das Flugzeug
Corps – Das Korps
Loaf – Das Brot
Extension – Die Erweiterung
Freeway – Die Autobahn
Solitude – Die Einsamkeit
Chemical – Die Chemische
Villager – Der Dorfbewohner
Perfection – Die Perfektion
Pope – Der Papst
Semester – Das Semester
Liver – Die Leber
Saucer – Die Untertasse
Urgency – Die Dringlichkeit
Volcano – Der Vulkan
Spice – Die Würze
Hostage – Die Geisel
Choir – Der Chor
Dough – Der Teig
Commotion – Die Aufregung
Courthouse – Gerichtsgebäude
Salmon – Der Lachs
Boxer – Der Boxer
Errand – Die Besorgung
Mechanism – Wobei Der Mechanismus
Telescope – Das Teleskop
Ferry – Die Fähre
Nigger – Der Nigger
PasserBy – Der Passant
Irritation – Die Reizung
Sedan – Die Limousine
Commitment – Das Engagement
Coward – Der Feigling
Git – Die Git
Flare – Die Fackel
Howl – Das Heulen
Fang – Die Fang
Roman – Die Römisch
Hue – Der Farbton
Discomfort – Das Unbehagen
Vent – Das Entlüftungs
Canoe – Das Kanu
Recipe – Das Rezept
Hamburger – Der Hamburger
Eave – Die Traufe
Barber – Der Barbier
Passing – Das Ableben
Betrayal – Der Verrat
Sweatshirt – Das Sweatshirt
Tentacle – Die Tentakel
Surf – Die Brandung
Plaid – Das Plaid
Walkway – Der Gehweg
Limp – Das Hinken
Administration – Die Verwaltung
Convenience – Die Bequemlichkeit
Diaper – Die Windel
Mole – Der Maulwurf
Cleaner – Der Reiniger
Swell – Die Dünung
GrownUp – Der Erwachsene
Scan – Die Scan
Clarity – Die Klarheit
Salon – Der Salon
Producer – Der Produzent
Flying – Die Flug
Plea – Der Rechtsmittelgrund
Prairie – Die Prärie
Passport – Der Pass
Alternative – Die Alternative
Vanity – Die Eitelkeit
Dam – Der Damm
Abuse – Der Missbrauch
Olive – Die Olive
Miner – Der Bergmann
Reserve – Die Reserve
Backup – Die Sicherungs
Intercom – Die Gegensprechanlage
Shawl – Das Tuch
Platter – Der Plattenteller
Implication – Die Implikation
Rumble – Das Poltern
Announcer – Der Ansager
Rubble – Die Trümmer
Axe – Die Axt
Transmission – Die Übertragungs
Crib – Die Krippe
Hop – Die Sprung
Graveyard – Der Friedhof
Aroma – Das Aroma
Dialogue – Der Dialog
Roller – Die Walze
Congregation – Gemeinde
Terrain – Das Gelände
Transfer – Der Transfer
Hardware – Die Hardware
Generator – Der Generator
Luxury – Die Luxus
Auditorium – Das Auditorium
Goblin – Der Kobold
Peg – Der Zapfen
Defeat – Die Niederlage
Haven – The Haven
Specimen – Die Probe
Hearth – Der Herd
Admission – Die Zulassung
Obsession – Die Besessenheit
Launch – Der Start
Patsy – Die Patsy
Dorm – Das Wohnheim
Glen – The Glen
Saw – Die Säge
Til – Die Til
Ape – Der Affe
Stagger – Der Staffelungs
Pussy – Die Fotze
Collector – Der Sammler
Earthquake – Das Erdbeben
Flake – Die Flocke
Syllable – Die Silbe
Bouquet – Das Bouquet
Selection – Die Auswahl
Vow – Der Schwur
Granddaughter – Die Enkelin
Symptom – Das Symptom
Scenario – Das Szenario
Riot – Der Aufruhr
Timing – Das Timing
Burger – Der Burger
Plus – Die Plus
Sparrow – Der Spatz
Embassy – Die Botschaft
Podium – Das Podium
Accusation – Der Vorwurf
Manor – Das Herrenhaus
Shuffling – Das Schlurfen
Dolphin – Der Delfin
Kettle – Der Wasserkocher
Trooper – Der Soldat
Salvation – Die Rettung
Vet – Der Tierarzt
Runway – Die Landebahn
Poppy – Der Mohn
Upstairs – Im Obergeschoss
Lava – Die Lava
Inspiration – Die Inspiration
Bosom – Der Busen
Intruder – Der Eindringling
Supermarket – Der Supermarkt
Trophy – Der Pokal
Jealousy – Die Eifersucht
Warden – Der Aufseher
Passageway – Der Durchgang
Marina – Der Yachthafen
Farewell – Das Lebewohl
Belongings – Die Gegenstände
Procession – Die Prozession
Astronaut – Der Astronaut
Crotch – Der Schritt
Sweep – Die Sweep
Recovery – Die Erholung
Harness – Der Kabelbaum
Anguish – Die Angst
Logo – Das Logo
Litter – Der Wurf
Marine – Die Marine
Resentment – Der Groll
CoOp – Der CoOp
Drake – The Drake
Gypsy – Der Zigeuner
Imitation – Die Nachahmung
Employer – Der Arbeitgeber
Freshman – Der Neuling
Phenomenon – Das Phänomen
Flute – Die Flöte
Greek – Der Grieche
Condo – Die Wohnung
Forefinger – Der Zeigefinger
Burial – Das Begräbnis
Republic – Die Republik
Emerald – Der Smaragd
Bathrobe – Der Bademantel
Testimony – Das Zeugnis
Hinge – Das Scharnier
Bakery – Die Bäckerei
Context – Der Kontext
Bargain – Das Schnäppchen
Saying – Das Sprichwort
Foreman – Der Vorarbeiter
Swan – Der Schwan
Flannel – Die Flanell
Indication – Die Angabe
Significance – Die Signifikanz
Beetle – Der Käfer
Learning – Die Lern
Pub – Das Lokal
Fraction – Die Fraktion
Trout – Die Forelle
Crust – Die Kruste
Overcoat – Die Überzugs
Glint – Das Glitzern
Medal – Die Medaille
Perception – Die Wahrnehmung
Welcome – Das Willkommen
Dictionary – Das Wörterbuch
Metaphor – Die Metapher
Poverty – Die Armut
Main – Die Haupt
Climb – Der Anstieg
Leash – Die Leine""".split('\n')

lst = [l.split('–') for l in lst]
for l in lst:
    if len(l)<2:
        print(l)
lst = [(a.strip(),b.strip()) for a,b in lst]
en_to_gr = dict(lst)
en_nouns = en_to_gr.keys()
gr_nouns = en_to_gr.values()

from collections import defaultdict
from random import choice, randint

class Question:
    seen = defaultdict(int)
    total = 0
    size = len(lst)

    def generate(self):
        for _ in range(10):
            tr, w = choice(lst)
            if self.seen[w]==0 or total >= size:
                break
        o2,o3 = choice(en_nouns), choice(en_nouns)
        i = randint(0,2)
        self.total += 1
        self.seen[w] += 1
        if i==0:
            return (i,w,tr,o2,o3)
        elif i==1:
            return (i,w,o2,tr,o3)
        else:
            return (i,w,o2,o3,tr)

if __name__ == "__main__":
    print(Question().generate())
